/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Delvi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanelFondo1 = new javax.swing.JPanel();
        NombreProyec1 = new javax.swing.JLabel();
        btnCoordinadores = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        lblCoordinador = new javax.swing.JLabel();
        lblite = new javax.swing.JLabel();
        lblslogan = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        imgTecnm = new javax.swing.JLabel();
        subfondo = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TecNM_logoaz.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(5, 5));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo1.setBackground(new java.awt.Color(0, 39, 68));
        PanelFondo1.setMinimumSize(new java.awt.Dimension(1024, 768));
        PanelFondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreProyec1.setBackground(new java.awt.Color(255, 255, 255));
        NombreProyec1.setFont(new java.awt.Font("Eras Bold ITC", 0, 56)); // NOI18N
        NombreProyec1.setForeground(new java.awt.Color(255, 255, 255));
        NombreProyec1.setText("cITEs");
        PanelFondo1.add(NombreProyec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 550, 60));

        btnCoordinadores.setBackground(new java.awt.Color(19, 35, 47));
        btnCoordinadores.setBorderPainted(false);
        btnCoordinadores.setFocusCycleRoot(true);
        btnCoordinadores.setFocusPainted(false);
        btnCoordinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordinadoresActionPerformed(evt);
            }
        });
        PanelFondo1.add(btnCoordinadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 140, 120));

        btnUsuario.setBackground(new java.awt.Color(15, 35, 50));
        btnUsuario.setBorderPainted(false);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        PanelFondo1.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 150, 120));

        lblCoordinador.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        lblCoordinador.setForeground(new java.awt.Color(255, 255, 255));
        lblCoordinador.setText("Coordinador");
        PanelFondo1.add(lblCoordinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        lblite.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblite.setForeground(new java.awt.Color(255, 255, 255));
        lblite.setText("Instituto Tecnologico de Ensenada");
        PanelFondo1.add(lblite, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, -1, 30));

        lblslogan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblslogan.setForeground(new java.awt.Color(255, 255, 255));
        lblslogan.setText("!Agenda tu cita y evita las esperas!");
        PanelFondo1.add(lblslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 30));

        lblUsuario1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setText("Usuario");
        PanelFondo1.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        imgTecnm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TecNM_logoaz.png"))); // NOI18N
        PanelFondo1.add(imgTecnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 470, -1));

        subfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abstract-luxurious-dark-navy-blue-background-with-golden-line-elegant-modern-background-illustration-vector.jpg"))); // NOI18N
        subfondo.setText("jLabel2");
        PanelFondo1.add(subfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -210, 1710, 1190));

        getContentPane().add(PanelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoordinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordinadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoordinadoresActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreProyec1;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JButton btnCoordinadores;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel imgTecnm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCoordinador;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblite;
    private javax.swing.JLabel lblslogan;
    private javax.swing.JLabel subfondo;
    // End of variables declaration//GEN-END:variables
}

//private javax.swing.JToggleButton BotonAlumnoInicio;: Boton para ingresar al inicio de alumno y/o se registre/cree cuenta
   // private javax.swing.JButton BotonCoordInicio; : boton para ingresar al inicio Coordinador y/o cree cuenta
    //private javax.swing.JLabel InsertarIconoAlum;:Icono de alumno
   // private javax.swing.JLabel NombreProyecto;: cITEs
    //private javax.swing.JPanel Panel1Inicio;  Panel azul de fondo
    //private javax.swing.JPanel Panel2Inicio;  Panel gris donde estarn los botones e iconos
    //private javax.swing.JLabel insertarIconoCoord;  : Icono de coordinador