/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import cites.Alumno;
import database.SqlAlumno;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FrAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form FrAlumnos
     */
    public FrAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelFondoRefe = new javax.swing.JPanel();
        jPanelFondoRefe = new javax.swing.JPanel();
        lblContrasenia = new javax.swing.JLabel();
        txtFieldCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        btnMostrarContra = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        jlabelClick = new javax.swing.JLabel();
        lblCites = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelFondoRefe.setBackground(new java.awt.Color(153, 204, 255));
        jpanelFondoRefe.setMinimumSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setPreferredSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasenia.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblContrasenia.setText("Contraseña:");
        jPanelFondoRefe.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        txtFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCorreoActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(txtFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 440, 30));

        lblCorreo.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblCorreo.setText("Correo Institucional:");
        jPanelFondoRefe.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 30));
        jPanelFondoRefe.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 260, 30));

        btnMostrarContra.setBackground(new java.awt.Color(242, 242, 242));
        btnMostrarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3844476-eye-see-show-view-watch_110339.png"))); // NOI18N
        btnMostrarContra.setBorderPainted(false);
        btnMostrarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContraActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(btnMostrarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 30, 30));

        BtnAceptar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 150, 50));

        BtnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnRegresar.setText("REGRESAR");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 150, 50));

        lblRegistro.setText("¿No estas registrado? Registrate Aqui ");
        jPanelFondoRefe.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, 30));

        lblBienvenida.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblBienvenida.setText("¡BIENVENIDO ALBATRO!");
        jPanelFondoRefe.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jlabelClick.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlabelClick.setForeground(new java.awt.Color(102, 102, 255));
        jlabelClick.setText("Click Aqui");
        jlabelClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelClickMouseClicked(evt);
            }
        });
        jPanelFondoRefe.add(jlabelClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 110, 30));

        jpanelFondoRefe.add(jPanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 860, 560));

        lblCites.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lblCites.setText("cITEs");
        jpanelFondoRefe.add(lblCites, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        getContentPane().add(jpanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        // 03/03/2024
        try{
            
        String correo = txtFieldCorreo.getText().trim();
        String contrasenia = new String(passwordField.getPassword());
        char[] passwordChars = passwordField.getPassword();
        
        String password = new String(passwordChars);
        
        if (correo.isEmpty()) {
            throw new IllegalArgumentException("El campo de correo electrónico está vacío.");
        }
        if (password.isEmpty()) {
            throw new IllegalArgumentException("El campo de contraseña está vacío.");
        }

        // Realizar la autenticación utilizando SqlAlumno
        SqlAlumno sqlAlumno = new SqlAlumno();
        Alumno alumno = sqlAlumno.consultarAlumno(contrasenia, correo);

        // Verificar si se encontró un alumno con las credenciales proporcionadas
        if (alumno.getId() != null) {
            // Si el alumno existe, mostrar la interfaz del menú principal
            FrMenuAlumnos menuAlumnos = new FrMenuAlumnos();
            menuAlumnos.setVisible(true);
            //Para que se cierre la ventana de inicio de sesión
            this.dispose();
        } else {
            // Si no se encontró un alumno, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }

        } catch (IllegalArgumentException e) {
        // Capturar la excepción e imprimir un mensaje de error
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
 } 
                                              

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        FrMenuPrincipal inicio = new FrMenuPrincipal();
        
        //Mostramos la interfaz del menu principal
        inicio.setVisible(true);
        
        //Para que se cierre la ventana 
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed
    
    private void txtFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCorreoActionPerformed
 
       
    }//GEN-LAST:event_txtFieldCorreoActionPerformed
    
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void jlabelClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelClickMouseClicked
        // TODO add your handling code here:
        FrRegistrarAlumnos registroAlumnos = new FrRegistrarAlumnos();
        
        //Mostramos la interfaz del menu principal
        registroAlumnos.setVisible(true);
        
        //Para que se cierre la ventana 
        this.dispose();
    }//GEN-LAST:event_jlabelClickMouseClicked

    private void btnMostrarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContraActionPerformed
        // TODO add your handling code here:
    if(btnMostrarContra.getText().equals("Mostrar")) {
        passwordField.setEchoChar((char)0); // Mostrar la contraseña
        
        btnMostrarContra.setText("Ocultar");
    } else {
        passwordField.setEchoChar('*'); // Ocultar la contraseña
        btnMostrarContra.setText("Mostrar");
    }
    }//GEN-LAST:event_btnMostrarContraActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton btnMostrarContra;
    private javax.swing.JPanel jPanelFondoRefe;
    private javax.swing.JLabel jlabelClick;
    private javax.swing.JPanel jpanelFondoRefe;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCites;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtFieldCorreo;
    // End of variables declaration//GEN-END:variables
}
