/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import cites.Coordinador;
import database.SqlCoordinador;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FrCoords extends javax.swing.JFrame {
    Coordinador usuario;
    

    /**
     * Creates new form FrAlumnos
     */
    public FrCoords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelFondoRefe = new javax.swing.JPanel();
        jPanelFondoRefe = new javax.swing.JPanel();
        lblContrasenia = new javax.swing.JLabel();
        txtNumEmpleado = new javax.swing.JTextField();
        lblNoEmpleado = new javax.swing.JLabel();
        btnMostrarContra = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        BtnAceptar = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        jLabelClick = new javax.swing.JLabel();
        lblCites = new javax.swing.JLabel();
        lblCiteslogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelFondoRefe.setBackground(new java.awt.Color(15, 35, 50));
        jpanelFondoRefe.setMinimumSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setPreferredSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRefe.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasenia.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblContrasenia.setText("Contraseña:");
        jPanelFondoRefe.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        txtNumEmpleado.setToolTipText("Ingrese su Num de Empleado");
        txtNumEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumEmpleadoActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(txtNumEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 270, 30));

        lblNoEmpleado.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblNoEmpleado.setText("No. de Empleado:");
        jPanelFondoRefe.add(lblNoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        btnMostrarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3844476-eye-see-show-view-watch_110339.png"))); // NOI18N
        btnMostrarContra.setBorderPainted(false);
        btnMostrarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContraActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(btnMostrarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 30, 30));

        passwordField.setToolTipText("Ingrese su Contraseña");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 260, 30));

        BtnAceptar.setBackground(new java.awt.Color(15, 35, 50));
        BtnAceptar.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Iniciar Sesión");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 150, 40));

        lblRegistro.setText("¿No esta registrado? Registrese Aqui ");
        jPanelFondoRefe.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, 30));

        lblBienvenida.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblBienvenida.setText("¡BIENVENIDO COORDINADOR!");
        jPanelFondoRefe.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabelClick.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelClick.setForeground(new java.awt.Color(25, 25, 183));
        jLabelClick.setText("Click Aqui");
        jLabelClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClickMouseClicked(evt);
            }
        });
        jPanelFondoRefe.add(jLabelClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, 30));

        lblCites.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lblCites.setForeground(new java.awt.Color(15, 35, 50));
        lblCites.setText("cITEs");
        jPanelFondoRefe.add(lblCites, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jpanelFondoRefe.add(jPanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 610, 770));

        lblCiteslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoCites.png"))); // NOI18N
        jpanelFondoRefe.add(lblCiteslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        getContentPane().add(jpanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClickMouseClicked
        // TODO add your handling code here:
        FrRegistrarCoords registroCoords = new FrRegistrarCoords();
        
        //Mostramos la interfaz del menu principal
        registroCoords.setVisible(true);
        
        //Para que se cierre la ventana 
        this.dispose();
    }//GEN-LAST:event_jLabelClickMouseClicked

    private void btnMostrarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContraActionPerformed
        // TODO add your handling code here:
    if(btnMostrarContra.getText().equals("Mostrar")) {
        passwordField.setEchoChar((char)0); // Mostrar la contraseña
        
        btnMostrarContra.setText("Ocultar");
    } 
    else {
        passwordField.setEchoChar('*'); // Ocultar la contraseña
        btnMostrarContra.setText("Mostrar");
    }
    }//GEN-LAST:event_btnMostrarContraActionPerformed

     private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        try{
            
        numControl = txtNumEmpleado.getText().trim();
        contrasenia = new String(passwordField.getPassword());
        char[] passwordChars = passwordField.getPassword();
        
        String password = new String(passwordChars);
        
        if (!numControl.matches("[0-9]+")) { // Utilizamos una expresión regular para verificar si hay caracteres que no sean dígitos
            throw new IllegalArgumentException("El número de empleado solo puede contener números."); // Lanzamos una excepción si se encuentran caracteres que no sean dígitos
        }
        if (password.isEmpty()) {
            throw new IllegalArgumentException("El campo de contraseña está vacío.");
        }

        // Realizar la autenticación utilizando SqlAlumno
        SqlCoordinador sqlCoordinador = new SqlCoordinador();
        Coordinador coordinador = sqlCoordinador.consultarCoordinador(contrasenia, numControl);

        // Verificar si se encontró un alumno con las credenciales proporcionadas
        if (coordinador.getId() != null) {
            this.usuario =  coordinador;
            // Si el coordinador existe, mostrar la interfaz del menú principal
            FrMenuCoords inicioCoords = new FrMenuCoords(this.usuario);
            inicioCoords.setVisible(true);
            //Para que se cierre la ventana de inicio de sesión
            this.dispose();
        } 
        else {
            // Si no se encontró un coordinador, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }
}
        catch (IllegalArgumentException e) {
        // Capturar la excepción e imprimir un mensaje de error
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }                                          

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
            FrMenuPrincipal inicio = new FrMenuPrincipal();
            inicio.setVisible(true);
            //Para que se cierre la ventana de inicio de sesión
            this.dispose();
    }                                           

     private void txtNumEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {}                                             

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCoords().setVisible(true);
            }
        });
    }

      // Variables globales
    String correo="", contrasenia="", numControl="";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton btnMostrarContra;
    private javax.swing.JLabel jLabelClick;
    private javax.swing.JPanel jPanelFondoRefe;
    private javax.swing.JPanel jpanelFondoRefe;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCites;
    private javax.swing.JLabel lblCiteslogo;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblNoEmpleado;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtNumEmpleado;
    // End of variables declaration//GEN-END:variables
}
