/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;


/**
 *
 * @author PC
 */
public class FrInicioAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form FrAlumnos
     */
    public FrInicioAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelFondoRefe = new javax.swing.JPanel();
        jPanelFondoRefe = new javax.swing.JPanel();
        lblHorarios = new javax.swing.JLabel();
        txtFieldDetalles = new javax.swing.JTextField();
        lblSeleccionCarrera = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        lblinstruccion = new javax.swing.JLabel();
        CmbCarrera = new javax.swing.JComboBox<>();
        CmbHorarios = new javax.swing.JComboBox<>();
        lblMotivos = new javax.swing.JLabel();
        CmbMotivos = new javax.swing.JComboBox<>();
        lblMotivos1 = new javax.swing.JLabel();
        lblCites = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelFondoRefe.setBackground(new java.awt.Color(153, 204, 255));
        jpanelFondoRefe.setMinimumSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setPreferredSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHorarios.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblHorarios.setText("Horarios Disponibles:");
        jPanelFondoRefe.add(lblHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));
        jPanelFondoRefe.add(txtFieldDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 690, 180));

        lblSeleccionCarrera.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblSeleccionCarrera.setText("Seleccione la coordinacion de su carrera:");
        jPanelFondoRefe.add(lblSeleccionCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        BtnAceptar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 150, 50));

        BtnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnRegresar.setText("REGRESAR");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 150, 50));

        lblinstruccion.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblinstruccion.setText("Rellene sus datos para agendar una cita ");
        jPanelFondoRefe.add(lblinstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        CmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCarreraActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(CmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 320, 30));

        CmbHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbHorariosActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(CmbHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 140, 30));

        lblMotivos.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblMotivos.setText("Motivo de la Cita:");
        jPanelFondoRefe.add(lblMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        CmbMotivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbMotivosActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(CmbMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 370, 30));

        lblMotivos1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblMotivos1.setText("Detalles de la cita:");
        jPanelFondoRefe.add(lblMotivos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        jpanelFondoRefe.add(jPanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 860, 580));

        lblCites.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lblCites.setText("cITEs");
        jpanelFondoRefe.add(lblCites, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        getContentPane().add(jpanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        FrMenuAlumnos menuAlumnos = new FrMenuAlumnos();
        
        //Mostramos la interfaz del menu principal
        menuAlumnos.setVisible(true);
        
        //Para que se cierre la ventana 
        this.dispose();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
       FrMenuAlumnos menuAlumnos = new FrMenuAlumnos();
        
        //Mostramos la interfaz del menu principal
        menuAlumnos.setVisible(true);
        
        //Para que se cierre la ventana 
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void CmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCarreraActionPerformed
         // TODO add your handling code here:
        if (CmbCarrera.getSelectedIndex() == -1) {
        // Lanza una excepción indicando que ningún ninguna coordiancion de carrera fue seleccionado
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una carrera.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
       
        // Aquí va el resto del código que deseas ejecutar cuando se ha seleccionado una coordinacion de carrera:
    }
    }//GEN-LAST:event_CmbCarreraActionPerformed
    }//GEN-LAST:event_CmbCarreraActionPerformed

    private void CmbHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbHorariosActionPerformed
        // TODO add your handling code here:
         if (CmbHorarios.getSelectedIndex() == -1) {
        // Lanza una excepción indicando que no se a seleccionado ningun horario 
        JOptionPane.showMessageDialog(null, "Por favor, seleccione el horario de preferencia  para su cita .", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
       
        // Aquí va el resto del código que deseas ejecutar cuando se ha seleccionado horario de cita :
    }
    }//GEN-LAST:event_CmbHorariosActionPerformed

    private void CmbMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbMotivosActionPerformed
        // TODO add your handling code here:
           if (CmbMotivos.getSelectedIndex() == -1) {
        // Lanza una excepción indicando que no se a seleccionado el motivo de cita 
        JOptionPane.showMessageDialog(null, "Por favor, seleccione el motivo de su cita .", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
       
        // Aquí va el resto del código que deseas ejecutar cuando se ha seleccionado motivo cita:
    }
    }//GEN-LAST:event_CmbMotivosActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrInicioAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CmbCarrera;
    private javax.swing.JComboBox<String> CmbHorarios;
    private javax.swing.JComboBox<String> CmbMotivos;
    private javax.swing.JPanel jPanelFondoRefe;
    private javax.swing.JPanel jpanelFondoRefe;
    private javax.swing.JLabel lblCites;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblMotivos;
    private javax.swing.JLabel lblMotivos1;
    private javax.swing.JLabel lblSeleccionCarrera;
    private javax.swing.JLabel lblinstruccion;
    private javax.swing.JTextField txtFieldDetalles;
    // End of variables declaration//GEN-END:variables
}
