package vista;

import cites.Alumno;
import cites.Cita;
import database.SqlCitas;
import database.SqlCoordinador;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
/**
 *
 * @author PC
 */
public class FrInicioAlumnos extends javax.swing.JFrame {
    Alumno usuario;
    /**
     * Creates new form FrAlumnos
     */
    public FrInicioAlumnos(Alumno usuario) {
        this.usuario = usuario;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelFondoRefe = new javax.swing.JPanel();
        jPanelFondoRefe = new javax.swing.JPanel();
        lblHorarios = new javax.swing.JLabel();
        lblSeleccionCarrera = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        lblinstruccion = new javax.swing.JLabel();
        CmbCarrera = new javax.swing.JComboBox<>();
        CmbHorarios = new javax.swing.JComboBox<>();
        lblMotivos = new javax.swing.JLabel();
        CmbMotivos = new javax.swing.JComboBox<>();
        lblMotivos1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADetalles = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cmboxDia = new javax.swing.JComboBox<>();
        cmboxMes = new javax.swing.JComboBox<>();
        cmboxAnio = new javax.swing.JComboBox<>();
        lblCites = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelFondoRefe.setBackground(new java.awt.Color(153, 204, 255));
        jpanelFondoRefe.setMinimumSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setPreferredSize(new java.awt.Dimension(1024, 768));
        jpanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRefe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHorarios.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblHorarios.setText("Horario:");
        jPanelFondoRefe.add(lblHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        lblSeleccionCarrera.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblSeleccionCarrera.setText("Seleccione la coordinacion de su carrera:");
        jPanelFondoRefe.add(lblSeleccionCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        BtnAceptar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 150, 50));

        BtnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BtnRegresar.setText("REGRESAR");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 150, 50));

        lblinstruccion.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblinstruccion.setText("Rellene sus datos para agendar una cita ");
        jPanelFondoRefe.add(lblinstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        SqlCoordinador SqlCoordinador = new SqlCoordinador();
        SqlCoordinador.mirarOpcionesCoordinacion();
        ArrayList<String> Coordinador= SqlCoordinador.mirarOpcionesCoordinacion();
        Iterator it = Coordinador.iterator();
        Vector carreras=new Vector();
        while (it.hasNext()){
            carreras.add(it.next());
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(carreras);
        CmbCarrera.setModel(model);
        CmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCarreraActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(CmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 320, 30));

        CmbHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:30", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00" }));
        CmbHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbHorariosActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(CmbHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 140, 30));

        lblMotivos.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblMotivos.setText("Motivo de la Cita:");
        jPanelFondoRefe.add(lblMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        CmbMotivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------", "Cambio de carrera", "Quejas", "Cambio de materias", "Dudas", "Otro", " " }));
        CmbMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbMotivosActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(CmbMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 370, 30));

        lblMotivos1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblMotivos1.setText("Detalles de la cita:");
        jPanelFondoRefe.add(lblMotivos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        txtADetalles.setColumns(10);
        txtADetalles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtADetalles.setLineWrap(true);
        txtADetalles.setRows(5);
        txtADetalles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtADetallesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtADetalles);

        jPanelFondoRefe.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 730, 200));

        jLabel1.setText("(maximo 175 caracters)");
        jPanelFondoRefe.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        cmboxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanelFondoRefe.add(cmboxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 100, 30));

        cmboxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Nobiembre", "Diciembre" }));
        jPanelFondoRefe.add(cmboxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 100, 30));

        cmboxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2024", "2025" }));
        cmboxAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxAnioActionPerformed(evt);
            }
        });
        jPanelFondoRefe.add(cmboxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 100, 30));

        jpanelFondoRefe.add(jPanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 860, 580));

        lblCites.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lblCites.setText("cITEs");
        jpanelFondoRefe.add(lblCites, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        getContentPane().add(jpanelFondoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        //Revisar que este correcta la informacion de etnrada
        if(this.revisarCorectitud()){
        //Obtener datos
        String cordinador = (String) CmbCarrera.getSelectedItem();
        String cordID = cordinador.split("-")[0];
        
        //int alumnoID =    TODO
        String alumnoID = this.usuario.getId();
        
        String motivos = (String) CmbMotivos.getSelectedItem();
        
        if (txtADetalles.getText().isEmpty()){
            motivos += ": "+ txtADetalles.getText();
        }
        
        String horaCmb = String.valueOf(CmbHorarios.getSelectedItem());
        String[] horaDividida = horaCmb.split(":");
        int horaMilitar = Integer.parseInt(horaDividida[0] + horaDividida[1]);
                
        int dia = cmboxDia.getSelectedIndex();
        int mes =  cmboxMes.getSelectedIndex();
        int anio = Integer.parseInt((String) cmboxAnio.getSelectedItem());
                
        String estado = "p";
        
        
        //Pasar datos a objeto cita
        Cita cita = new Cita();
        
        cita.setCitadorId(cordID);
        cita.setCitadorDocente(alumnoID);
        cita.setMotivo(motivos);
        cita.setEstado(estado);
        cita.setAnio(anio);
        cita.setMes(mes);
        cita.setDia(dia);
        cita.setHora(horaMilitar);
                
        SqlCitas db = new SqlCitas();
        db.crearCita(cita);
        
        // Si salio correcto
        JOptionPane.showMessageDialog(null, "Se ha agendado la cita");
        FrMenuAlumnos menuAlumnos = new FrMenuAlumnos(this.usuario);
        menuAlumnos.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
       FrMenuAlumnos menuAlumnos = new FrMenuAlumnos(this.usuario);
        
        //Mostramos la interfaz del menu principal
        menuAlumnos.setVisible(true);
        
        //Para que se cierre la ventana 
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void CmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCarreraActionPerformed
         // TODO add your handling code here:
        if (CmbCarrera.getSelectedIndex() == -1) {
        // Lanza una excepción indicando que ningún ninguna coordiancion de carrera fue seleccionado
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una carrera.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
       
        // Aquí va el resto del código que deseas ejecutar cuando se ha seleccionado una coordinacion de carrera:
    }
                                              
    }//GEN-LAST:event_CmbCarreraActionPerformed

    private void CmbHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbHorariosActionPerformed

    }//GEN-LAST:event_CmbHorariosActionPerformed

    private void CmbMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbMotivosActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_CmbMotivosActionPerformed

    //Codigo para tener maximo de palabras
    private void txtADetallesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtADetallesKeyPressed

        int max = 175;
    if(txtADetalles.getText().length() > max+1) {
        evt.consume();
        String shortened = txtADetalles.getText().substring(0, max);
        txtADetalles.setText(shortened);
    }else if(txtADetalles.getText().length() > max) {
        evt.consume();
    }

    }//GEN-LAST:event_txtADetallesKeyPressed

    private void cmboxAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboxAnioActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrInicioAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* 
        SqlCoordinador SqlCoordinador = new SqlCoordinador();
        SqlCoordinador.mirarOpcionesCoordinacion();  
        ArrayList<String> Coordinador= SqlCoordinador.mirarOpcionesCoordinacion();
        Iterator it = Coordinador.iterator();
        Vector carreras=new Vector();
        while (it.hasNext()){
         carreras.add("Sarahí Castaños Lafarga - Sistemas");
         carreras.add("Ismael Hernández Capuchin - Mecatronica");
         carreras.add("María Mayté Loera Sánchez - Industrial");
        }
        
        DefaultComboBoxModel model = new DefaultComboBoxModel(carreras); 
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alumno alumno = new Alumno();
                new FrInicioAlumnos(alumno).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CmbCarrera;
    private javax.swing.JComboBox<String> CmbHorarios;
    private javax.swing.JComboBox<String> CmbMotivos;
    private javax.swing.JComboBox<String> cmboxAnio;
    private javax.swing.JComboBox<String> cmboxDia;
    private javax.swing.JComboBox<String> cmboxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFondoRefe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelFondoRefe;
    private javax.swing.JLabel lblCites;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblMotivos;
    private javax.swing.JLabel lblMotivos1;
    private javax.swing.JLabel lblSeleccionCarrera;
    private javax.swing.JLabel lblinstruccion;
    private javax.swing.JTextArea txtADetalles;
    // End of variables declaration//GEN-END:variables

    private boolean revisarCorectitud() {
        boolean bandera = true;
         if (CmbMotivos.getSelectedIndex() == 0) {
             bandera = false;
             JOptionPane.showMessageDialog(null, "Por favor, seleccione el motivo de su cita .", "Error", JOptionPane.ERROR_MESSAGE);
         } else
        if (CmbCarrera.getSelectedIndex() == 0){
            bandera = false;
            JOptionPane.showMessageDialog(null, "Seleccione a la coordinacion con quien quiere agendar cita");
        } else
        if (cmboxMes.getSelectedIndex() == 0){
            bandera = false;
            JOptionPane.showMessageDialog(null, "Seleccione el mes en el quie quiere agendar cita");
        } else
        if (cmboxDia.getSelectedIndex() == 0){
            bandera = false;
            JOptionPane.showMessageDialog(null, "Seleccione el dia en el quie quiere agendar cita");
        } else
            
        if (cmboxAnio.getSelectedIndex() == 0){
            bandera = false;
            JOptionPane.showMessageDialog(null, "Seleccione el anio en el quie quiere agendar cita");
        } else  
        if (CmbHorarios.getSelectedIndex() == 0){
            bandera = false;
            JOptionPane.showMessageDialog(null, "Seleccione el horario en el quie quiere agendar cita");
        }
       return bandera;
    }
}
