/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import cites.Coordinador;

/**
 *
 * @author Usuario
 */
public class FrMenuCoords extends javax.swing.JFrame {
    Coordinador usuario;
    
    /**
     * Creates new form Inicio
     */
    public FrMenuCoords(Coordinador usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoRef = new javax.swing.JPanel();
        btnVerPerfil = new javax.swing.JButton();
        lblVerCitas1 = new javax.swing.JLabel();
        lblLogoCites = new javax.swing.JLabel();
        btnCitasPendientes = new javax.swing.JButton();
        btnVerCitas = new javax.swing.JButton();
        lblCitasPendie = new javax.swing.JLabel();
        lblVerCitas = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRef.setBackground(new java.awt.Color(15, 35, 50));
        jPanelFondoRef.setForeground(new java.awt.Color(15, 35, 50));
        jPanelFondoRef.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanelFondoRef.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanelFondoRef.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerPerfil.setBackground(new java.awt.Color(15, 35, 50));
        btnVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgCoord.png"))); // NOI18N
        btnVerPerfil.setBorderPainted(false);
        btnVerPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilActionPerformed(evt);
            }
        });
        jPanelFondoRef.add(btnVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 190, 110));

        lblVerCitas1.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblVerCitas1.setForeground(new java.awt.Color(255, 255, 255));
        lblVerCitas1.setText("VER PERFIL");
        jPanelFondoRef.add(lblVerCitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, -1, -1));

        lblLogoCites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoCites.png"))); // NOI18N
        jPanelFondoRef.add(lblLogoCites, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btnCitasPendientes.setBackground(new java.awt.Color(15, 35, 50));
        btnCitasPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/citasPendientes.png"))); // NOI18N
        btnCitasPendientes.setBorderPainted(false);
        btnCitasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasPendientesActionPerformed(evt);
            }
        });
        jPanelFondoRef.add(btnCitasPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 180, 110));

        btnVerCitas.setBackground(new java.awt.Color(15, 35, 50));
        btnVerCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verCitas.png"))); // NOI18N
        btnVerCitas.setBorderPainted(false);
        btnVerCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });
        jPanelFondoRef.add(btnVerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 190, 110));

        lblCitasPendie.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblCitasPendie.setForeground(new java.awt.Color(255, 255, 255));
        lblCitasPendie.setText("VER CITAS PENDIENTES");
        jPanelFondoRef.add(lblCitasPendie, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        lblVerCitas.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblVerCitas.setForeground(new java.awt.Color(255, 255, 255));
        lblVerCitas.setText("VER CITAS");
        jPanelFondoRef.add(lblVerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/azulFondo.jpg"))); // NOI18N
        jPanelFondoRef.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -120, 2140, 1030));

        getContentPane().add(jPanelFondoRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        //TODO    NOTA 
        //La ventana FrCitasRegistradas es para los alumnos, parece que nos falta una ventana para coordinadores
        
        //FrCitasRegistradas citasRegistradas = new FrCitasRegistradas();
        
        //citasRegistradas.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void btnCitasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasPendientesActionPerformed
        // TODO add your handling code here:
        FrCitasPendientes citasPendientes = new FrCitasPendientes();
        
        //Mostramos la interfaz de Ver Citas
        citasPendientes.setVisible(true);
        
        //Cierre de Ventana
        this.dispose();
    }//GEN-LAST:event_btnCitasPendientesActionPerformed

    private void btnVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilActionPerformed
       // TODO add your handling code here:
        FrPerfilCoordinador perfil = new FrPerfilCoordinador(this.usuario);
        
        //Mostramos la interfaz de Ver Citas
        perfil.setVisible(true);
        
        //Cierre de Ventana
        this.dispose();
    }//GEN-LAST:event_btnVerPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenuCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenuCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenuCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenuCoords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Coordinador coord = new Coordinador();
                new FrMenuCoords(coord).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCitasPendientes;
    private javax.swing.JButton btnVerCitas;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.JPanel jPanelFondoRef;
    private javax.swing.JLabel lblCitasPendie;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoCites;
    private javax.swing.JLabel lblVerCitas;
    private javax.swing.JLabel lblVerCitas1;
    // End of variables declaration//GEN-END:variables
}
