/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import cites.Alumno;

/**
 *
 * @author Usuario
 */
public class FrMenuAlumnos extends javax.swing.JFrame {
    //Objeto que representa el usuario
    Alumno usuario;

    /**
     * Creates new form Inicio
     */
    public FrMenuAlumnos(Alumno usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoRef = new javax.swing.JPanel();
        jpanelsubfondo = new javax.swing.JPanel();
        lblCuenta = new javax.swing.JLabel();
        btnCuenta = new javax.swing.JButton();
        lblVerCitas = new javax.swing.JLabel();
        btnVerCitas = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        lblCites = new javax.swing.JLabel();
        lblAgendar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRef.setBackground(new java.awt.Color(153, 204, 255));
        jPanelFondoRef.setForeground(new java.awt.Color(15, 35, 50));
        jPanelFondoRef.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanelFondoRef.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanelFondoRef.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelsubfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuenta.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblCuenta.setText("Ver mi cuenta");
        jpanelsubfondo.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        btnCuenta.setBackground(new java.awt.Color(242, 242, 242));
        btnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user_84308.png"))); // NOI18N
        btnCuenta.setBorderPainted(false);
        btnCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });
        jpanelsubfondo.add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 100, 100));

        lblVerCitas.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblVerCitas.setText("VER MIS CITAS");
        jpanelsubfondo.add(lblVerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        btnVerCitas.setBackground(new java.awt.Color(242, 242, 242));
        btnVerCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/appointment_calendar_tasks_icon_152025.png"))); // NOI18N
        btnVerCitas.setBorderPainted(false);
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });
        jpanelsubfondo.add(btnVerCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 180, 110));

        lblBienvenida.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblBienvenida.setText("¡Bienvenido Albatro!");
        jpanelsubfondo.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        btnAgendar.setBackground(new java.awt.Color(242, 242, 242));
        btnAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quote_request_icon_217006.png"))); // NOI18N
        btnAgendar.setBorderPainted(false);
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jpanelsubfondo.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, 110));

        lblCites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoCites.png"))); // NOI18N
        jpanelsubfondo.add(lblCites, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        lblAgendar.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblAgendar.setText("AGENDAR UNA CITA");
        jpanelsubfondo.add(lblAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jpanelsubfondo.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 100, 30));

        jPanelFondoRef.add(jpanelsubfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 840, 620));

        lblite.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblite.setText("INSTITUTO TECNOLOGICO DE ENSENADA");
        jPanelFondoRef.add(lblite, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        getContentPane().add(jPanelFondoRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1040, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
        // TODO add your handling code here:
        FrPerfilUsuario Usuario = new FrPerfilUsuario(this.usuario);
        
        //Mostramos la interfaz de ver mi usuario
        Usuario.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnCuentaActionPerformed

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        // TODO add your handling code here:
        FrCitasRegistradas citasRegistradas = new FrCitasRegistradas(this.usuario);
        
        //Mostramos la interfaz de Ver Citas
        citasRegistradas.setVisible(true);
        
        //Cierre de Ventana
        this.dispose();
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        FrInicioAlumnos inicioAlumnos = new FrInicioAlumnos(this.usuario);
        
        //Mostramos la interfaz para agendar citas
        inicioAlumnos.setVisible(true);
        
        //Cierre de Ventana
        this.dispose(); 
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrMenuPrincipal inicio = new FrMenuPrincipal();
        
        //Mostramos la interfaz para agendar citas
        inicio.setVisible(true);
        
        //Cierre de Ventana
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alumno alumno = new Alumno();
                new FrMenuAlumnos(alumno).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnCuenta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerCitas;
    private javax.swing.JPanel jPanelFondoRef;
    private javax.swing.JPanel jpanelsubfondo;
    private javax.swing.JLabel lblAgendar;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCites;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblVerCitas;
    private javax.swing.JLabel lblite;
    // End of variables declaration//GEN-END:variables
}
