/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class FrMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public FrMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoRef = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCoords = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        lblAlumno1 = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoRef.setBackground(new java.awt.Color(15, 35, 50));
        jPanelFondoRef.setForeground(new java.awt.Color(15, 35, 50));
        jPanelFondoRef.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanelFondoRef.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanelFondoRef.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoCites.png"))); // NOI18N
        jPanelFondoRef.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btnCoords.setBackground(new java.awt.Color(15, 35, 50));
        btnCoords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgCoord.png"))); // NOI18N
        btnCoords.setBorderPainted(false);
        btnCoords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordsActionPerformed(evt);
            }
        });
        jPanelFondoRef.add(btnCoords, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 180, -1));

        btnUsuario.setBackground(new java.awt.Color(15, 35, 50));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgUsuario.png"))); // NOI18N
        btnUsuario.setBorderPainted(false);
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanelFondoRef.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 190, 110));

        lblAlumno1.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblAlumno1.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno1.setText("COORDINADORES");
        jPanelFondoRef.add(lblAlumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        lblAlumno.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno.setText("ALUMNOS");
        jPanelFondoRef.add(lblAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/azulFondo.jpg"))); // NOI18N
        jPanelFondoRef.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -40, 2140, 1030));

        getContentPane().add(jPanelFondoRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
        FrAlumnos Alumnos = new FrAlumnos();
        
        //Mostramos la interfaz del Alumnos
        Alumnos.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnCoordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordsActionPerformed
        // TODO add your handling code here:
        FrCoords Coordinadores = new FrCoords();
        
        //Mostramos la interfaz de Coordinadores
        Coordinadores.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCoordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoords;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFondoRef;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblAlumno1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
